// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod sensors {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
    use super::_rt;
    #[repr(u8)]
    #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
    pub enum ReadError {
        IndexOutOfRange,
        InvalidHandleType,
        InvalidHandle,
    }
    impl ReadError {
        pub fn name(&self) -> &'static str {
            match self {
                ReadError::IndexOutOfRange => "index-out-of-range",
                ReadError::InvalidHandleType => "invalid-handle-type",
                ReadError::InvalidHandle => "invalid-handle",
            }
        }
        pub fn message(&self) -> &'static str {
            match self {
                ReadError::IndexOutOfRange => "",
                ReadError::InvalidHandleType => "",
                ReadError::InvalidHandle => "",
            }
        }
    }
    impl ::core::fmt::Debug for ReadError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("ReadError")
                .field("code", &(*self as i32))
                .field("name", &self.name())
                .field("message", &self.message())
                .finish()
        }
    }
    impl ::core::fmt::Display for ReadError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            write!(f, "{} (error {})", self.name(), * self as i32)
        }
    }
    impl std::error::Error for ReadError {}
    impl ReadError {
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> ReadError {
            if !cfg!(debug_assertions) {
                return ::core::mem::transmute(val);
            }
            match val {
                0 => ReadError::IndexOutOfRange,
                1 => ReadError::InvalidHandleType,
                2 => ReadError::InvalidHandle,
                _ => panic!("invalid enum discriminant"),
            }
        }
    }
    pub type TimeUs = u32;
    #[repr(u8)]
    #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
    pub enum SensorKind {
        Line,
        Imu,
        Angle,
    }
    impl ::core::fmt::Debug for SensorKind {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
                SensorKind::Line => f.debug_tuple("SensorKind::Line").finish(),
                SensorKind::Imu => f.debug_tuple("SensorKind::Imu").finish(),
                SensorKind::Angle => f.debug_tuple("SensorKind::Angle").finish(),
            }
        }
    }
    impl SensorKind {
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> SensorKind {
            if !cfg!(debug_assertions) {
                return ::core::mem::transmute(val);
            }
            match val {
                0 => SensorKind::Line,
                1 => SensorKind::Imu,
                2 => SensorKind::Angle,
                _ => panic!("invalid enum discriminant"),
            }
        }
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct SensorIndexRange {
        pub start: u8,
        pub count: u8,
    }
    impl ::core::fmt::Debug for SensorIndexRange {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("SensorIndexRange")
                .field("start", &self.start)
                .field("count", &self.count)
                .finish()
        }
    }
    pub type SensorValue = i16;
    pub type SensorValues = _rt::Vec<SensorValue>;
    pub type FutureHandle = u32;
    #[derive(Clone, Copy)]
    pub enum AsyncVoidResult {
        Blocked,
        Ready,
    }
    impl ::core::fmt::Debug for AsyncVoidResult {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
                AsyncVoidResult::Blocked => {
                    f.debug_tuple("AsyncVoidResult::Blocked").finish()
                }
                AsyncVoidResult::Ready => {
                    f.debug_tuple("AsyncVoidResult::Ready").finish()
                }
            }
        }
    }
    #[derive(Clone)]
    pub enum AsyncSensorResult {
        Blocked,
        Ready(SensorValues),
    }
    impl ::core::fmt::Debug for AsyncSensorResult {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
                AsyncSensorResult::Blocked => {
                    f.debug_tuple("AsyncSensorResult::Blocked").finish()
                }
                AsyncSensorResult::Ready(e) => {
                    f.debug_tuple("AsyncSensorResult::Ready").field(e).finish()
                }
            }
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn current_time() -> TimeUs {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "current-time"]
                fn wit_import0() -> i32;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0() -> i32 {
                unreachable!()
            }
            let ret = unsafe { wit_import0() };
            ret as u32
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn sleep_blocking_for(us: TimeUs) -> () {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "sleep-blocking-for"]
                fn wit_import0(_: i32);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32) {
                unreachable!()
            }
            unsafe { wit_import0(_rt::as_i32(us)) };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn sleep_blocking_until(us: TimeUs) -> () {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "sleep-blocking-until"]
                fn wit_import0(_: i32);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32) {
                unreachable!()
            }
            unsafe { wit_import0(_rt::as_i32(us)) };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn read_sensor_blocking(
        sensor: SensorKind,
        indexes: SensorIndexRange,
    ) -> Result<SensorValues, ReadError> {
        unsafe {
            #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
            #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
            struct RetArea(
                [::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()],
            );
            let mut ret_area = RetArea(
                [::core::mem::MaybeUninit::uninit(); 3
                    * ::core::mem::size_of::<*const u8>()],
            );
            let SensorIndexRange { start: start0, count: count0 } = indexes;
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "read-sensor-blocking"]
                fn wit_import2(_: i32, _: i32, _: i32, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: i32, _: i32, _: i32, _: *mut u8) {
                unreachable!()
            }
            unsafe {
                wit_import2(
                    sensor.clone() as i32,
                    _rt::as_i32(start0),
                    _rt::as_i32(count0),
                    ptr1,
                )
            };
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result8 = match l3 {
                0 => {
                    let e = {
                        let l4 = *ptr1
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l5 = *ptr1
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len6 = l5;
                        _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
                    };
                    Ok(e)
                }
                1 => {
                    let e = {
                        let l7 = i32::from(
                            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                        );
                        ReadError::_lift(l7 as u8)
                    };
                    Err(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            };
            result8
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn sleep_async_for(us: TimeUs) -> FutureHandle {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "sleep-async-for"]
                fn wit_import0(_: i32) -> i32;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32) -> i32 {
                unreachable!()
            }
            let ret = unsafe { wit_import0(_rt::as_i32(us)) };
            ret as u32
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn sleep_async_until(us: TimeUs) -> FutureHandle {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "sleep-async-until"]
                fn wit_import0(_: i32) -> i32;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32) -> i32 {
                unreachable!()
            }
            let ret = unsafe { wit_import0(_rt::as_i32(us)) };
            ret as u32
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn read_sensor_async(
        sensor: SensorKind,
        sensor_index_range: SensorIndexRange,
    ) -> FutureHandle {
        unsafe {
            let SensorIndexRange { start: start0, count: count0 } = sensor_index_range;
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "read-sensor-async"]
                fn wit_import1(_: i32, _: i32, _: i32) -> i32;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i32, _: i32) -> i32 {
                unreachable!()
            }
            let ret = unsafe {
                wit_import1(
                    sensor.clone() as i32,
                    _rt::as_i32(start0),
                    _rt::as_i32(count0),
                )
            };
            ret as u32
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn poll_timer(handle: FutureHandle) -> Result<AsyncVoidResult, ReadError> {
        unsafe {
            #[repr(align(1))]
            struct RetArea([::core::mem::MaybeUninit<u8>; 2]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "poll-timer"]
                fn wit_import1(_: i32, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                unreachable!()
            }
            unsafe { wit_import1(_rt::as_i32(handle), ptr0) };
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result6 = match l2 {
                0 => {
                    let e = {
                        let l3 = i32::from(*ptr0.add(1).cast::<u8>());
                        let v4 = match l3 {
                            0 => AsyncVoidResult::Blocked,
                            n => {
                                debug_assert_eq!(n, 1, "invalid enum discriminant");
                                AsyncVoidResult::Ready
                            }
                        };
                        v4
                    };
                    Ok(e)
                }
                1 => {
                    let e = {
                        let l5 = i32::from(*ptr0.add(1).cast::<u8>());
                        ReadError::_lift(l5 as u8)
                    };
                    Err(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            };
            result6
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn poll_sensor(handle: FutureHandle) -> Result<AsyncSensorResult, ReadError> {
        unsafe {
            #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
            #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
            struct RetArea(
                [::core::mem::MaybeUninit<u8>; 4 * ::core::mem::size_of::<*const u8>()],
            );
            let mut ret_area = RetArea(
                [::core::mem::MaybeUninit::uninit(); 4
                    * ::core::mem::size_of::<*const u8>()],
            );
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "poll-sensor"]
                fn wit_import1(_: i32, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                unreachable!()
            }
            unsafe { wit_import1(_rt::as_i32(handle), ptr0) };
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result9 = match l2 {
                0 => {
                    let e = {
                        let l3 = i32::from(
                            *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                        );
                        let v7 = match l3 {
                            0 => AsyncSensorResult::Blocked,
                            n => {
                                debug_assert_eq!(n, 1, "invalid enum discriminant");
                                let e7 = {
                                    let l4 = *ptr0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *ptr0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len6 = l5;
                                    _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
                                };
                                AsyncSensorResult::Ready(e7)
                            }
                        };
                        v7
                    };
                    Ok(e)
                }
                1 => {
                    let e = {
                        let l8 = i32::from(
                            *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                        );
                        ReadError::_lift(l8 as u8)
                    };
                    Err(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            };
            result9
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn forget_handle(handle: FutureHandle) -> () {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "sensors")]
            unsafe extern "C" {
                #[link_name = "forget-handle"]
                fn wit_import0(_: i32);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32) {
                unreachable!()
            }
            unsafe { wit_import0(_rt::as_i32(handle)) };
        }
    }
}
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod motors {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
    use super::_rt;
    pub type MotorPower = i16;
    #[allow(unused_unsafe, clippy::all)]
    pub fn set_power(left: MotorPower, right: MotorPower) -> () {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "motors")]
            unsafe extern "C" {
                #[link_name = "set-power"]
                fn wit_import0(_: i32, _: i32);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, _: i32) {
                unreachable!()
            }
            unsafe { wit_import0(_rt::as_i32(left), _rt::as_i32(right)) };
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod robot {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() = super::super::__link_custom_section_describing_imports;
        use super::super::_rt;
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct Color {
            pub r: u8,
            pub g: u8,
            pub b: u8,
        }
        impl ::core::fmt::Debug for Color {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.debug_struct("Color")
                    .field("r", &self.r)
                    .field("g", &self.g)
                    .field("b", &self.b)
                    .finish()
            }
        }
        #[derive(Clone)]
        pub struct Configuration {
            pub name: _rt::String,
            pub color_main: Color,
            pub color_secondary: Color,
            pub width_axle: i32,
            pub length_front: i32,
            pub length_back: i32,
            pub clearing_back: i32,
            pub wheel_radius: i32,
            pub gear_ratio_num: i32,
            pub gear_ratio_den: i32,
            pub front_sensors_spacing: i32,
            pub front_sensors_height: i32,
        }
        impl ::core::fmt::Debug for Configuration {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.debug_struct("Configuration")
                    .field("name", &self.name)
                    .field("color-main", &self.color_main)
                    .field("color-secondary", &self.color_secondary)
                    .field("width-axle", &self.width_axle)
                    .field("length-front", &self.length_front)
                    .field("length-back", &self.length_back)
                    .field("clearing-back", &self.clearing_back)
                    .field("wheel-radius", &self.wheel_radius)
                    .field("gear-ratio-num", &self.gear_ratio_num)
                    .field("gear-ratio-den", &self.gear_ratio_den)
                    .field("front-sensors-spacing", &self.front_sensors_spacing)
                    .field("front-sensors-height", &self.front_sensors_height)
                    .finish()
            }
        }
        #[doc(hidden)]
        #[allow(non_snake_case)]
        pub unsafe fn _export_setup_cabi<T: Guest>() -> *mut u8 {
            #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
            let result0 = T::setup();
            let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
            let Configuration {
                name: name2,
                color_main: color_main2,
                color_secondary: color_secondary2,
                width_axle: width_axle2,
                length_front: length_front2,
                length_back: length_back2,
                clearing_back: clearing_back2,
                wheel_radius: wheel_radius2,
                gear_ratio_num: gear_ratio_num2,
                gear_ratio_den: gear_ratio_den2,
                front_sensors_spacing: front_sensors_spacing2,
                front_sensors_height: front_sensors_height2,
            } = result0;
            let vec3 = (name2.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
            let Color { r: r4, g: g4, b: b4 } = color_main2;
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (_rt::as_i32(
                r4,
            )) as u8;
            *ptr1.add(1 + 2 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (_rt::as_i32(
                g4,
            )) as u8;
            *ptr1.add(2 + 2 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (_rt::as_i32(
                b4,
            )) as u8;
            let Color { r: r5, g: g5, b: b5 } = color_secondary2;
            *ptr1.add(3 + 2 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (_rt::as_i32(
                r5,
            )) as u8;
            *ptr1.add(4 + 2 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (_rt::as_i32(
                g5,
            )) as u8;
            *ptr1.add(5 + 2 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (_rt::as_i32(
                b5,
            )) as u8;
            *ptr1.add(8 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                width_axle2,
            );
            *ptr1.add(12 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                length_front2,
            );
            *ptr1.add(16 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                length_back2,
            );
            *ptr1.add(20 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                clearing_back2,
            );
            *ptr1.add(24 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                wheel_radius2,
            );
            *ptr1.add(28 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                gear_ratio_num2,
            );
            *ptr1.add(32 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                gear_ratio_den2,
            );
            *ptr1.add(36 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                front_sensors_spacing2,
            );
            *ptr1.add(40 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                front_sensors_height2,
            );
            ptr1
        }
        #[doc(hidden)]
        #[allow(non_snake_case)]
        pub unsafe fn __post_return_setup<T: Guest>(arg0: *mut u8) {
            let l0 = *arg0.add(0).cast::<*mut u8>();
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l0, l1, 1);
        }
        #[doc(hidden)]
        #[allow(non_snake_case)]
        pub unsafe fn _export_run_cabi<T: Guest>() {
            #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
            T::run();
        }
        pub trait Guest {
            fn setup() -> Configuration;
            fn run() -> ();
        }
        #[doc(hidden)]
        macro_rules! __export_robot_cabi {
            ($ty:ident with_types_in $($path_to_types:tt)*) => {
                const _ : () = { #[unsafe (export_name = "robot#setup")] unsafe extern
                "C" fn export_setup() -> * mut u8 { unsafe { $($path_to_types)*::
                _export_setup_cabi::<$ty > () } } #[unsafe (export_name =
                "cabi_post_robot#setup")] unsafe extern "C" fn _post_return_setup(arg0 :
                * mut u8,) { unsafe { $($path_to_types)*:: __post_return_setup::<$ty >
                (arg0) } } #[unsafe (export_name = "robot#run")] unsafe extern "C" fn
                export_run() { unsafe { $($path_to_types)*:: _export_run_cabi::<$ty > ()
                } } };
            };
        }
        #[doc(hidden)]
        pub(crate) use __export_robot_cabi;
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct _RetArea(
            [::core::mem::MaybeUninit<u8>; 40 + 3 * ::core::mem::size_of::<*const u8>()],
        );
        static mut _RET_AREA: _RetArea = _RetArea(
            [::core::mem::MaybeUninit::uninit(); 40
                + 3 * ::core::mem::size_of::<*const u8>()],
        );
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_line_follower_robot_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: exports::robot::__export_robot_cabi!($ty with_types_in
        $($path_to_types_root)*:: exports::robot);
    };
}
#[doc(inline)]
pub(crate) use __export_line_follower_robot_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:line-follower-robot:line-follower-robot:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1200] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa6\x08\x01A\x02\x01\
A\x06\x01B'\x01m\x03\x12index-out-of-range\x13invalid-handle-type\x0einvalid-han\
dle\x04\0\x0aread-error\x03\0\0\x01y\x04\0\x07time-us\x03\0\x02\x01m\x03\x04line\
\x03imu\x05angle\x04\0\x0bsensor-kind\x03\0\x04\x01r\x02\x05start}\x05count}\x04\
\0\x12sensor-index-range\x03\0\x06\x01|\x04\0\x0csensor-value\x03\0\x08\x01p\x09\
\x04\0\x0dsensor-values\x03\0\x0a\x01y\x04\0\x0dfuture-handle\x03\0\x0c\x01q\x02\
\x07blocked\0\0\x05ready\0\0\x04\0\x11async-void-result\x03\0\x0e\x01q\x02\x07bl\
ocked\0\0\x05ready\x01\x0b\0\x04\0\x13async-sensor-result\x03\0\x10\x01@\0\0\x03\
\x04\0\x0ccurrent-time\x01\x12\x01@\x01\x02us\x03\x01\0\x04\0\x12sleep-blocking-\
for\x01\x13\x04\0\x14sleep-blocking-until\x01\x13\x01j\x01\x0b\x01\x01\x01@\x02\x06\
sensor\x05\x07indexes\x07\0\x14\x04\0\x14read-sensor-blocking\x01\x15\x01@\x01\x02\
us\x03\0\x0d\x04\0\x0fsleep-async-for\x01\x16\x04\0\x11sleep-async-until\x01\x16\
\x01@\x02\x06sensor\x05\x12sensor-index-range\x07\0\x0d\x04\0\x11read-sensor-asy\
nc\x01\x17\x01j\x01\x0f\x01\x01\x01@\x01\x06handle\x0d\0\x18\x04\0\x0apoll-timer\
\x01\x19\x01j\x01\x11\x01\x01\x01@\x01\x06handle\x0d\0\x1a\x04\0\x0bpoll-sensor\x01\
\x1b\x01@\x01\x06handle\x0d\x01\0\x04\0\x0dforget-handle\x01\x1c\x03\0\x07sensor\
s\x05\0\x01B\x04\x01|\x04\0\x0bmotor-power\x03\0\0\x01@\x02\x04left\x01\x05right\
\x01\x01\0\x04\0\x09set-power\x01\x02\x03\0\x06motors\x05\x01\x01B\x08\x01r\x03\x01\
r}\x01g}\x01b}\x04\0\x05color\x03\0\0\x01r\x0c\x04names\x0acolor-main\x01\x0fcol\
or-secondary\x01\x0awidth-axlez\x0clength-frontz\x0blength-backz\x0dclearing-bac\
kz\x0cwheel-radiusz\x0egear-ratio-numz\x0egear-ratio-denz\x15front-sensors-spaci\
ngz\x14front-sensors-heightz\x04\0\x0dconfiguration\x03\0\x02\x01@\0\0\x03\x04\0\
\x05setup\x01\x04\x01@\0\x01\0\x04\0\x03run\x01\x05\x04\0\x05robot\x05\x02\x04\0\
1component:line-follower-robot/line-follower-robot\x04\0\x0b\x19\x01\0\x13line-f\
ollower-robot\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x07\
0.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
